name: masterclass_atividades
description: Aplicativo desenvolvido como atividade do curso Masterclass Flutterando

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  package_info: ^2.0.2
  path_provider: ^2.0.9
  url_launcher: ^6.0.20
  font_awesome_flutter: ^9.2.0
  percent_indicator: ^4.0.0
  flutter_launcher_icons: ^0.9.2
  mask_text_input_formatter: ^2.1.0
  intl: ^0.17.0
  dio: ^4.0.4
  shared_preferences: ^2.0.13
  dartion: ^1.0.7
  
flutter_icons:
  image_path_ios: "images/logo/logo.png"
  image_path_android: "images/logo/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  modular_test: ^1.0.1+1
  build_runner: ^2.1.7
  mocktail: ^0.0.1-dev.12

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/glasses.png
   - images/glasses@2x.png
   - images/glasses@3x.png
   - images/running.png
   - images/running@2x.png
   - images/running@3x.png
   - images/toys.png
   - images/toys@2x.png
   - images/toys@3x.png
   - images/logo/logo.png
   - images/logo/logo@2x.png
   - images/logo/logo@3x.png
   - images/logotinder.png
   - images/apple.png
   - images/facebook.png
   - images/conversation.png
   - images/dev.jpg
   - img/logo.png
   - img/google.png
   - img/logoII.png
   - img/purp.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
